name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1

      - name: Install Dependancies
        run: bun install

      - name: Build Package
        run: bun run build
