name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1

      - name: Setup NPM
        uses: actions/setup-node@v3

      - name: Configure Github User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install Dependancies
        run: bun install

      - name: Bump Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Build Package
        run: bun run build

      - name: Authenticate With NPM
        run: |
          echo "@tlscipher:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Package
        run: npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}